version: '3.8'

services:
  geolocationapi:
    image: carmenpuccio/geolocationapi:latest
    ports:
      - target: 5254
        x-aws-protocol: http
    environment:
        - ASPNETCORE_ENVIRONMENT=Production
        - ASPNETCORE_URLS=http://+:5254
        - HealtcheckBaseURL=http://localhost:5254/api/v1/geolocation/
        - HealtcheckIPToTest=8.8.8.8
x-aws-cloudformation:
    Resources:
        Geolocationapi5254TargetGroup:
            Properties:
                HealthCheckPath: /hc
                Matcher:
                    HttpCode: 200