version: '3.8'

services:
  geolocationapi:
    image: geolocationapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - OTEL_OTLP_ENDPOINT=http://aws-otel-collector:4317
    volumes:
      - ~/.vsdbg:/remote_debugger:rw

