version: '3.8'

services:
  geolocationapi:
    image: geolocationapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
      - OTEL_OTLP_ENDPOINT=http://aws-otel-collector:4317

