version: '3.8'

services:
  geolocationapi:
    image: geolocationapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5254
      - OTEL_OTLP_ENDPOINT=http://aws-otel-collector:4317
      - HealtcheckBaseURL=http://localhost:5254/api/v1/geolocation/
      - HealtcheckIPToTest=8.8.8.8
    volumes:
      - ~/.vsdbg:/remote_debugger:rw

