apiVersion: v1
kind: Namespace
metadata:
  name: geolocationapi
  labels:
    name: geolocationapi
--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: geolocationapi
  name: geolocationapi
  namespace: geolocationapi
spec: 
  ports: 
    - 
      name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector: 
    app: geolocationapi
--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: geolocationapi
  name: geolocationapi
  namespace: geolocationapi
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: geolocationapi
  strategy: 
    type: Recreate
  template: 
    metadata: 
      labels: 
        app: geolocationapi
    spec: 
      containers: 
        - image: "carmenpuccio/geolocationapi_nginx:latest"
          name: nginx
          env: 
            - name: NGINX_PORT
              value: "80"
            - name: GEOLOCATIONAPI_HOST
              value: localhost
            - name: GEOLOCATIONAPI_PORT
              value: "5000"
          ports: 
            - containerPort: 80
              name: nginx
          livenessProbe:
            httpGet:
              path: /hc
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /hc
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 1             
        - image: "carmenpuccio/geolocationapi:latest"
          name: geolocationapi
          env: 
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: ASPNETCORE_URLS
              value: "http://+:5000"
          ports: 
            - containerPort: 5000
              name: geolocationapi