apiVersion: v1
kind: Namespace
metadata:
  name: geolocationapi
  labels:
    name: geolocationapi
--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: geolocationapi
  name: geolocationapi
  namespace: geolocationapi
spec: 
  ports: 
    - 
      name: http
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector: 
    app: geolocationapi
--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: geolocationapi
  name: geolocationapi
  namespace: geolocationapi
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: geolocationapi
  strategy: 
    type: Recreate
  template: 
    metadata: 
      labels: 
        app: geolocationapi
    spec: 
      containers: 
        - image: "carmenpuccio/aws-otel-collector:latest"
          name: aws-otel-collector           
        - image: "carmenpuccio/geolocationapi:latest"
          name: geolocationapi
          env: 
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: ASPNETCORE_URLS
              value: "http://+:5000"
            - name: OTEL_OTLP_ENDPOINT
              value: "http://localhost:4317"
            - name: HealtcheckBaseURL
              value: "http://localhost:5000/api/v1/geolocation/"
            - name: HealtcheckIPToTest
              value: "8.8.8.8"
          ports: 
            - containerPort: 5000
              name: geolocationapi
          livenessProbe:
            httpGet:
              path: /hc
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /hc
              port: 5000
            initialDelaySeconds: 5
            timeoutSeconds: 1  